# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickblock',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblock_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblock_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblockimage',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblockimage_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblockimage',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblockimage_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblocktype_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblocktype_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
